language: python

python:
    - 3.6

install:
    - pip install pipenv -i https://mirrors.aliyun.com/pypi/simple/ 
    - pipenv install -d

script:
    - make cov
    - make build

after_success:
    - codecov

deploy:
    provider: releases
    api_key:
        secure: ${GITHUB_TOKEN}
    file: dist/aiosqlite3-*-py3-none-any.whl
    skip_cleanup: true
    on:
        tags: true
